name: Mengting Hu
description: Mengting Hu's personal page
menu:
 - page: About
   url: /homepage/index
 - page: Papers
   url: /homepage/papers
 - page: Curriculum Vitae
   url: /homepage/cv
   links:
    - title: Experience
      url: "#experience"
    - title: Education
      url: "#education"
 - page: Teaching
   url: /homepage/teaching
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: hmt2014.github.io
locale: en_GB
