name: Mengting Hu
description: Mengting Hu's personal page
menu:
 - page: About
   url: "#about"
 - page: Papers
   url: "#papers"
 - page: Curriculum Vitae
   url: "#curriculum-vitae"
 - page: Teaching
   url: "#teaching"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: hmt2014.github.io
locale: en_GB
